language: go

go:
  - master

services:
  - mongodb
  - redis

script: BASEAPI_ENV=testing go test ./...

go_import_path: github.com/IoThingsDev/api
  
notifications:
  email: false

before_install:
  - openssl genrsa -out base.rsa 1024
  - openssl rsa -in base.rsa -pubout > base.rsa.pub
