version: '2'
services:
  redis-db:
    image: redis:latest
  mongo-db:
    image: mongo:latest
  api:
    container_name: iothings-api
    build: .
    ports: 
      - "4000:4000"
    links:
      - mongo-db:mongo
      - redis-db:redis
#  web:
#    build: ./admin
#    ports:
#     - "0.0.0.0:4200:4200"  
#    links:
#     - "api:api" 