version: '2'
services:
  mongo-db:
      image: mongo:latest

  redis-db:
      image: redis:latest

  serve:
    container_name: iothings
    build: .
    #command: go run main.go

    #environment:
    #  ENV: prod
    links:
      - mongo-db
      - redis-db
    ports:
      - "4000:4000"

  # FIXME(hoatle): $ docker-compose up test should work repeatedly
  test:
    build: .
    command: go run tests/main_test.go
    #environment:
    #  NODE_ENV: development

